version: "3"

services:
  client:
    build: .
    restart: always
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - ./client:/app
  server:
    build: ../backend-nest
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      POSTGRES_PASSWORD: password
  db:
    image: postgres
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DATABASE: reader_nest
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres_data:
